apiVersion: v1
kind: ConfigMap
metadata:
  name: career-ai-frontend-config
  namespace: career-ai-prod
data:
  config.js: |
    window.__APP_CONFIG__ = {
      API_BASE_URL: "http://51.21.151.4:5000",
      APP_ENV: "production"
    };
